spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stockdb?createDatabaseIfNotExist=true  
    username: root
    password: sac@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    #initialization-mode: always


  jpa:
    hibernate:
      ddl-auto: create  
    properties:
      hibernate:
        show_sql: true
        format_sql: true

